sonar.projectKey=uroojbutt_cohort-9-mern-16173-urooj
sonar.organization=uroojbutt

sonar.sources=frontend/src,backend/src
sonar.exclusions=**/*.spec.ts,**/*.mocha.spec.ts,**/*.test.jsx,**/node_modules/**

# Coverage exclusions (0% baseline files ko metric calculation se hata dega)
sonar.coverage.exclusions=\
  backend/src/main.ts,\
  backend/src/**/*.module.ts,\
  backend/src/auth/strategies/*.ts,\
  backend/src/**/*.dto.ts,\
  frontend/src/main.jsx,\
  frontend/src/api/api.js,\
  frontend/src/context/**/*.jsx,\
  frontend/src/components/auth-layout/**,\
  frontend/src/components/dashboard-actions/**,\
  frontend/src/components/empty-state/**,\
  frontend/src/components/buttons/**,\
  frontend/src/components/header/**,\
  frontend/src/components/loading-spinner/**,\
  frontend/src/components/note-card/**,\
  frontend/src/components/notes-grid/**,\
  frontend/src/components/protected-route/**,\
  frontend/src/pages/profile/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info